"""Add quantity to PortfolioAsset

Revision ID: 6c52539f3f53
Revises: a7d948c7e3a0
Create Date: 2025-05-03 19:43:05.341969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c52539f3f53'
down_revision: Union[str, None] = 'a7d948c7e3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_assets', sa.Column('quantity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_assets', 'quantity')
    # ### end Alembic commands ###
